##############################################################################
# Part of the Agnos RPC Framework
#    http://agnos.sourceforge.net
#
# Copyright 2010, Tomer Filiba (tomerf@il.ibm.com; tomerfiliba@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################

from SCons.Errors import UserError

try:
	Import("env")
except UserError:
	env = DefaultEnvironment()
	env["CPPDEFINES"] = {}
	if int(ARGUMENTS.get('AGNOS_DEBUG', 0)):
		env["CPPDEFINES"]["AGNOS_DEBUG"] = None
	if int(ARGUMENTS.get('BOOST_PROCESS_SUPPORTED', 0)):
		env["CPPDEFINES"]["BOOST_PROCESS_SUPPORTED"] = None

Decider('MD5')

env.Library('agnos', Glob('src/*.cpp')) 

