##############################################################################
# Part of the Agnos RPC Framework
#    http://agnos.sourceforge.net
#
# Copyright 2010, International Business Machines Corp.
#                 Author: Tomer Filiba (tomerf@il.ibm.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################

import os
import shutil

Decider('MD5')

env = DefaultEnvironment()
env["JARCHDIR"] = os.path.join(env.Dir('.').get_abspath(), 'build')

class_files = Java(target = "build", source = "src")
agnos_jar = Jar(target = "agnos.jar", source = "build")

def generate_javadoc(target, source, env):
    srcdir = source[0].path
    trgdir = target[0].path
    shutil.rmtree(trgdir, True)
    java_files = [os.path.join(dirpath, fn) 
        for dirpath, dirnames, filenames in os.walk(srcdir)
            for fn in filenames]    
    print "generating javadoc:"
    os.system("javadoc -d %s %s" % (trgdir, " ".join(java_files)))

env.Command("doc", "src", generate_javadoc)
Depends("doc", class_files)

agnos_jar = agnos_jar[0]
Return("agnos_jar")
