##############################################################################
# Part of the Agnos RPC Framework
#    http://agnos.sourceforge.net
#
# Copyright 2010, Tomer Filiba (tomerf@il.ibm.com; tomerfiliba@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##############################################################################

import os

Decider('MD5')

env = DefaultEnvironment()
env["JARCHDIR"] = os.path.join(env.Dir('.').get_abspath(), 'classes')

class_files = Java(target = "classes", source = "src")
agnos_jar = Jar(target = "agnos.jar", source = "classes")

agnos_jar = agnos_jar[0]
Return("agnos_jar")
